public class _11_Exception {
    // public static void main(String[] args) {
    //     System.out.println("Main method task started");

    //     try {
    //         Thread.sleep(5000);
    //     } catch (InterruptedException e) {
    //         e.printStackTrace();
    //     }

    //     System.out.println("Main method task completed");
    // }

    //                                          OR
    public static void main(String[] args) throws InterruptedException{
        System.out.println("Main method task started");

        
        Thread.sleep(5000);
        

        System.out.println("Main method task completed");
    }
}
/*
 * checked expection : compiler will check the possibilty of exception
 * exception occurs only at runtime
 */
/*
===========================================
REVISION NOTES FOR THE GIVEN PROGRAM
===========================================

-------------------------------------------------------
1. WHAT THE ENTIRE PROGRAM DOES
-------------------------------------------------------
The program prints a start message, pauses the execution of the main
thread for 5 seconds using Thread.sleep(), and then prints a completion
message.  
It demonstrates handling of a checked exception (InterruptedException)
in two different ways:
  • using try–catch  
  • using throws in the method header

-------------------------------------------------------
2. DEFINITIONS OF IMPORTANT CONCEPTS USED IN THIS PROGRAM
-------------------------------------------------------

• Thread.sleep(milliseconds)
  Causes the currently executing thread to pause (go to timed waiting
  state) for the specified time.

• InterruptedException (Checked Exception)
  Occurs if another thread interrupts the sleeping thread.
  Since it is a checked exception, the compiler forces you to either
  handle it (try–catch) or declare it (throws).

• Checked Exception
  An exception type that the compiler checks at compile time and requires
  explicit handling or declaration.

-------------------------------------------------------
3. USAGE OF EACH CONCEPT IN THIS PROGRAM
-------------------------------------------------------

• Thread.sleep(5000)
  Pauses main thread execution for 5 seconds.

• try–catch block (commented version)
  Used to catch InterruptedException if sleep is interrupted.

• throws InterruptedException (active version)
  Declares that main() may throw InterruptedException, removing the need
  for a try–catch inside main().

• InterruptedException
  The only possible exception generated by Thread.sleep().

-------------------------------------------------------
4. PURPOSE OF EACH METHOD, BLOCK, AND STRUCTURE
-------------------------------------------------------

• main() method (commented version)
  Demonstrates handling a checked exception using try–catch.

• main() method (active version)
  Demonstrates handling a checked exception by declaring throws.

• System.out.println() statements
  Indicate start and completion of main method execution.

• Thread.sleep(5000)
  Causes a deliberate pause of 5 seconds between the two print statements.

-------------------------------------------------------
5. COMPLETE CONTROL FLOW FROM START TO END
-------------------------------------------------------

1. Program enters main().
2. Prints: “Main method task started”.
3. Executes Thread.sleep(5000):
      → Main thread pauses for 5 seconds.
      → If interrupted, InterruptedException would be thrown.
      → Because main() declares throws, the exception would propagate.
4. After the pause, prints: “Main method task completed”.
5. Program ends normally.

-------------------------------------------------------
6. EXACT RUNTIME BEHAVIOR
-------------------------------------------------------

Actual output (with a 5-second pause in between):

    Main method task started
    (5 second delay)
    Main method task completed

No additional messages appear unless InterruptedException occurs.

-------------------------------------------------------
END OF REVISION NOTES
-------------------------------------------------------
*/
